### ISSUE TITLE
comentarios sobre su primer sprint 

### ISSUE THREAD

**Issue by Jonhks** [brenduchiz/cdmx-2018-06-bc-core-am-social-network#17]
@AngieMonroe , @brenduchiz. 
- La interfaz es poco intuitiva para registrar un nuevo usuario. 
- Ya que se crea una nueva cuenta el modal debería cerrarse al darle click en guardar. 
- Se traba cuando me registro e intento ingresar. 
- Que es el archivo .visualCode? 
- No se debería de subir la carpeta de node_modules. 
- Todos los archivos js deberían ir dentro de la carpeta js. 
- Que es la carpeta vendor? Es un template, cierto? 
- Solo debería haber un solo archivo html al entrar al proyecto, si usarán mas archivos de este tipo, deben ir dentro de la carpeta views.
- Por buena practica un poyecto solo debe de tener un README.md
- Si van a usar imagenes, todas las imagenes es bueno tenerlas en la carpeta de imagenes. 
- REcuerden que su código debería estar enfocado a los test. Les dejo una lectura que espero les pueda servir: https://medium.com/javascript-scene/5-common-misconceptions-about-tdd-unit-tests-863d5beb3ce9. 
- Los scripts de firebase deben de ir justo antes de cerrar el body, sobre los demas scripts .
- El arhivo de index.html no se puede abrir. 
- Recuerden tener en cuenta y hacer código enfocado a Test, con esto me refiero a la separación de responsabilidades de los archivos js y hacer las funciones puras para poder testearlas.
- El archivo data.js y app.js, tienen muchas cosas iguales. Recuerden que cada archivo debe hacer algo diferente con responsabilidades divididas. 
- Nunca dejen de aprender y no se den por vencidas 😄!

**Comment by AngieMonroe** [comment]
Gracias, consideramos los puntos y trabajamos sobre ellos. Esperamos haberlos cubierto todos

**Comment by brenduchiz** [comment]
Exacto daremos nuestro mejor esfuerzo, gracias por las recomendaciones.

2018-07-31 19:30 GMT-05:00 AngieMonroe <notifications@github.com>:

**Comment by brenduchiz** [comment]
Exacto daremos nuestro mejor esfuerzo, gracias por las recomendaciones.😃
