### ISSUE TITLE
Pintar nombre 

### ISSUE THREAD

**Issue by brenduchiz** [brenduchiz/cdmx-2018-06-bc-core-am-social-network#2]

**Comment by brenduchiz** [comment]
Tenemos que investigar local storage para resolver este problema

**Comment by AngieMonroe** [comment]
Pinta el nombre del usuario de google, falta recuperar el nombre del usuario que se registra con correo y contraseña.

**Comment by brenduchiz** [comment]
- [:-1: ] pinta nombre correo ¿se logro ?

-   [ :+1:] pinta nombre google
@AngieMonroe
